# Generated by Django 4.2.7 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_adress_table_remove_restaurant_menu_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_table',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('PREMIUM', 'PREMIUM'), ('COMFORT', 'COMFORT'), ('BUSSINES', 'BUSSINES'), ('ELITE', 'ELITE')], max_length=225),
        ),
    ]
