# Generated by Django 4.2.7 on 2023-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_adress_table_name_alter_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('PREMIUM', 'PREMIUM'), ('ELITE', 'ELITE'), ('COMFORT', 'COMFORT'), ('BUSSINES', 'BUSSINES')], max_length=225),
        ),
    ]
