# Generated by Django 4.2.7 on 2023-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_alter_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('ELITE', 'ELITE'), ('BUSSINES', 'BUSSINES'), ('PREMIUM', 'PREMIUM'), ('COMFORT', 'COMFORT')], max_length=225),
        ),
    ]
